#ifndef GOBO_CORE_STM32F10X_CONFIG_H_
#define GOBO_CORE_STM32F10X_CONFIG_H_

#define GOBO_CONFIG_PLATFORM_INFO "stm32f10x"

#ifndef GOBO_CONFIG_LOG_OUTPUT
#define GOBO_CONFIG_LOG_OUTPUT GOBO_CONFIG_LOG_OUTPUT_PLATFORM_DEFINED
#endif

#define GOBO_CONFIG_ENABLE_PLATFORM_USEC_TIMER 1

#ifndef GOBO_PLATFORM_USE_PSEUDO_RESET
#define GOBO_PLATFORM_USE_PSEUDO_RESET 0
#endif

#endif // GOBO_CORE_STM32F10X_CONFIG_H_
